x-restart-policy: &restart_policy
  restart: unless-stopped
  logging:
    driver: loki
    options:
      loki-url: "http://loki:3100/loki/api/v1/push"

services:
  loki:
    image: grafana/loki:2.8.3
    expose:
      - "3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config:/etc/loki
      - loki-data:/loki
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'loki.cloudnativedays.jp -> http://loki:3100'
      STAGE: 'production' # Don't use production until staging works
    volumes:
      - https-portal-data:/var/lib/https-portal
    depends_on:
      - loki
  node-exporter:
    <<: *restart_policy
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100

volumes:
  https-portal-data:
  loki-data:
    external: true
